version: '3.7'

services:

  app:
    restart: always
    build:
      context: ./backend
    ports:
      - "8090:8090/udp"
    volumes:
      - ./backend/.local:/.local
      - ./backend/.keys:/.keys
    env_file:
      - .env
    environment:
      - DOCKER=1

  proxy:
    restart: always
    build:
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - app


